name: legal_doc_simplifier
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.2.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.0
  google_sign_in: ^6.2.1
  path_provider: ^2.1.1
  pdfx: ^2.3.0
  image_picker: ^1.1.2
  pdf: ^3.10.8
  file_picker:
    git:
      url: https://github.com/millatip/mobileCDR.git
  http: ^1.5.0
  syncfusion_flutter_pdf: ^24.1.41
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bgimage2.svg
    - assets/images/HomePageBG.png
    - assets/icons/google_logo.png
    - assets/icons/doubt.png
    - assets/icons/language_icon.png
    - assets/images/bg.svg
    - assets/images/girl_image.svg
    - assets/images/rectangle.svg

  fonts:
    - family: ArchitectsDaughter
      fonts:
        - asset: assets/fonts/Architects_Daughter/ArchitectsDaughter-Regular.ttf
    - family: ComingSoon
      fonts:
        - asset: assets/fonts/Coming_Soon/ComingSoon-Regular.ttf
