import 'package:flutter/material.dart';
//import 'package:flutter_svg/svg.dart';
//import 'package:legal_doc_simplifier/views/homepage/background_layout.dart';
import 'dart:io';
//import 'package:image_picker/image_picker.dart';
//import 'package:path_provider/path_provider.dart';
import 'package:legal_doc_simplifier/views/homepage/camera_button.dart';
import 'package:legal_doc_simplifier/views/homepage/upload_button.dart';
import 'package:legal_doc_simplifier/views/upload_screen/show_pdf_overlay.dart';
import 'package:legal_doc_simplifier/views/camera_screen/pdf_generator.dart';
//import 'package:legal_doc_simplifier/views/homepage/background_layout.dart';

const Color ourRed = Color(0xFFC10547);

class HomeBody extends StatelessWidget {
  const HomeBody({super.key});

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Positioned.fill(
          child: Image.asset('assets/images/HomePageBG.png', fit: BoxFit.cover),
        ),
        Column(
          mainAxisAlignment: MainAxisAlignment.end,
          children: [
            Text(
              "GET STARTED\nWITH A DOCUMENT NOW !!!",
              style: TextStyle(
                fontFamily: "ComingSoon",
                fontSize: 18,
                fontWeight: FontWeight.w400,
              ),
              textAlign: TextAlign.center,
            ),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                uploadButton(context),
                SizedBox(width: MediaQuery.of(context).size.width * 0.25),
                cameraButton((List<File> imageFiles) async {
                  final pdfFile = await generatePdfToTemp(imageFiles);

                  if (pdfFile.existsSync()) {
                    showPdfOverlay(
                      context,
                      title: 'Confirm PDF',
                      pdfFile: pdfFile,
                    );
                  } else {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text('PDF generation failed')),
                    );
                  }
                }),
              ],
            ),
            SizedBox(height: MediaQuery.of(context).size.height * 0.05),
          ],
        ),

        //Below code is for the preview of pdf generated by camera button
      ],
    );
  }
}
